//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UAFWinEd.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_RESCHANGE_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_WALLSETPIC                  131
#define IDD_ITEMS                       132
#define IDD_MAPSTYLE                    133
#define IDD_SHOP                        134
#define IDD_BGSETPIC                    135
#define IDD_TEXT_EVENT                  136
#define IDD_LEVELLIST                   137
#define IDD_SPELLS                      138
#define IDD_GLOBALDATA                  140
#define IDD_CHURCH                      141
#define IDD_TAVERN                      142
#define IDD_CHARACTER                   143
#define IDD_GETFILENAME                 144
#define IDD_SCROLLPICTUREDLG            145
#define IDD_TRAININGHALL                148
#define IDD_FILEOPENPREVIEW             153
#define IDD_ZONEDLG                     155
#define IDD_ADDNPC                      157
#define IDD_CAMPEVENT                   158
#define IDD_COMBAT                      159
#define IDD_COMBATTREASURE              160
#define IDD_DAMAGE                      161
#define IDD_ENCOUNTER                   162
#define IDD_CHOOSEITEMS                 163
#define IDD_BUTTONS                     164
#define IDD_CHOOSEMONSTERS              166
#define IDD_PASSWORD                    167
#define IDD_GIVEEXPERIENCE              168
#define IDD_TOUREVENT                   169
#define IDD_NPCSAYS                     170
#define IDD_REMOVENPC                   172
#define IDD_SMALLPICPOOL                173
#define IDD_SMALLPICDLG                 174
#define IDD_ICONPICDLG                  175
#define IDD_ITEMDB                      176
#define IDD_3DPICDLG                    178
#define IDD_3DPICDLG_640x480g_640x480e  178
#define IDD_BACKGROUNDPICDLG            179
#define IDD_WALLPICDLG                  180
#define IDD_DESIGNLIST                  185
#define IDD_ICONPICPOOL                 186
#define IDD_MAGICALITEMPROPERTIES       187
#define IDD_MONSTERDB                   188
#define IDD_CHOOSESPECIALABILITIES      190
#define IDD_DBUTILS                     191
#define IDD_ENTRYPOINTDLG               194
#define IDD_TRANSFERDLG                 195
#define IDD_PICSELECTDLG                196
#define IDD_STEPEVENTS                  198
#define IDD_GETMONEY                    199
#define IDD_TELEPORTDLG                 200
#define IDD_WHOPAYSDLG                  201
#define IDD_WHOTRIES                    203
#define IDD_SPECIALITEMDLG              204
#define IDD_PASSTIMEDLG                 205
#define IDD_QLISTBUTTONS                206
#define IDD_QBUTTONS                    207
#define IDD_QYESNO                      208
#define IDD_VAULTDATADIALOG             209
#define IDD_EVENTVIEWER                 212
#define IDD_SMALLTOWN                   214
#define IDD_ITEMKEYQUESTDLG             216
#define IDD_ADDSPECIALOBJECT            217
#define IDD_QUESTDLG                    218
#define IDD_UTILITIESEVENTDLG           220
#define IDD_SOUNDCHOOSER                222
#define IDI_PLAYARROW                   223
#define IDI_PLAYSTOP                    224
#define IDD_GLOBALSOUNDS                225
#define IDD_SOUNDEVENTDLG               226
#define IDD_SPELLEDITOR                 228
#define IDD_ITEMEDITOR                  229
#define IDD_MONSTEREDITOR               230
#define IDD_CHARACTEREDITOR             231
#define IDD_CHOOSENPC                   232
#define IDD_CHOOSEMONSTER               233
#define IDD_GAMEVERSION                 234
#define IDD_ANIMATIONSTYLE              235
#define IDD_ACCESS                      237
#define IDD_IMPORTFRUADATA              238
#define IDD_ASKSURE                     239
#define IDD_TAKEITEMS                   240
#define IDR_MAPpopup                    243
#define IDD_HEALPARTY                   245
#define IDD_LOGICBLOCK                  246
#define IDD_3DPICDLG_1024x768           248
#define IDD_SPELLATTRIBUTEEDIT          249
#define IDD_RUNTIMEATTRIBUTESELECT      250
#define IDD_3DPICDLG_800x600            251
#define IDD_3DPICDLG_800x600g_800x600e  251
#define IDD_3DPICDLG_1152x864           252
#define IDD_3DPICDLG_1280x1024          253
#define IDD_SPELLDBDLGEX                254
#define IDD_MONEYDATA                   256
#define IDD_RANDOMEVENT                 257
#define IDD_CHOOSECOMBATMONSTER         258
#define IDD_COMBATMONSTERDATA           259
#define IDD_DIFFLVLDATA                 260
#define IDD_DIFFLVLSETTINGS             261
#define IDD_ATTRIBUTEEDIT               262
#define IDD_ATTRIBUTEDATAEDIT           263
#define IDD_EDITOROPTIONS               266
#define IDD_GETMONEYSACKDATA            267
#define IDD_MONSTERATTACKDLG            268
#define IDD_MONSTERATTACKDETAILS        269
#define IDD_PLAYMOVIEFULLSCREEN         270
#define IDD_DESIGNSTATS                 271
#define IDD_JOURNALEDITOR               272
#define IDD_JOURNALENTRYDATA            273
#define IDD_JOURNALEVENT                274
#define IDD_TITLESCREEN                 275
#define IDD_TITLESCREENDATA             276
#define IDD_STARTINGEQUIPDLG            277
#define IDD_SPECIALKEYBLOCKAGE          278
#define IDD_TEXTEDIT                    279
#define IDD_SPECABMSGTYPES              280
#define IDD_GETSPECABMSG                281
#define IDD_3DPICDLG_640x480g_1024x768e 282
#define IDD_3DPICDLG_800x600g_1024x768e 283
#define IDD_3DPICDLG_640x480g_800x600e  284
#define IDD_3DPICDLG_800x600g_1280x1024e 285
#define IDD_3DPICDLG_640x480g_1280x1024e 286
#define IDD_TESTPARTY                   287
#define IDD_SEARCHPARAMS                288
#define IDD_TIMEEVENTS                  289
#define IDD_IMPORTWARNING               290
#define IDD_CrossReference              291
#define IDD_CLASSES                     294
#define IDD_EditTrainable               296
#define IDD_DIALOG1                     297
#define IDD_CHOOSEASLS                  298
#define IDD_CHOOSEOPTIONS               298
#define IDD_TAVERNTALES                 299
#define IDD_COMBAT_TREASURE             300
#define IDD_HELP                        301
#define IDD_FlowControl                 306
#define IDC_RESTEXT                     1001
#define IDC_PLACELEFT                   1002
#define IDC_RES640                      1002
#define IDC_MAPWIDTH                    1003
#define IDC_PLACERIGHT                  1003
#define IDC_UAPATH                      1003
#define IDC_RES800                      1003
#define IDC_MAPHEIGHT                   1004
#define IDC_SELECTCURRENT               1004
#define IDC_UASELECT                    1004
#define IDC_RES1024                     1004
#define IDC_PLACECURRENT                1005
#define IDC_DESIGNPATH                  1005
#define IDC_INSTALLTEXT                 1007
#define IDC_SLOT1                       1008
#define IDC_640CONFIG                   1008
#define IDC_SLOT2                       1009
#define IDC_800CONFIG                   1009
#define IDC_SLOT3                       1010
#define IDC_1024CONFIG                  1010
#define IDC_SLOT4                       1011
#define IDC_SLOT5                       1012
#define IDC_SLOT6                       1013
#define IDC_SLOT7                       1014
#define IDC_SLOT8                       1015
#define IDC_SLOT9                       1016
#define IDC_SLOT10                      1017
#define IDC_SLOT11                      1018
#define IDC_SLOT12                      1019
#define IDC_SLOT13                      1020
#define IDC_SLOT14                      1021
#define IDC_WISDOM                      1022
#define IDC_CHAR                        1022
#define IDC_PCNTCHANCE                  1022
#define IDC_TEXT                        1022
#define IDC_PLATINUM                    1022
#define IDC_SLOT15                      1022
#define IDC_SLOT16                      1023
#define IDC_PARTYXTRIGGER               1023
#define IDC_STRENGTH                    1024
#define IDC_PCNTHITPOINTS               1024
#define IDC_MORALE                      1024
#define IDC_GEMS                        1024
#define IDC_SLOTCOLOR1                  1024
#define IDC_PARTYYTRIGGER               1024
#define IDC_DEXTERITY                   1025
#define IDC_JEWELRY                     1025
#define IDC_SLOTCOLOR2                  1025
#define IDC_PAYJEWELS                   1025
#define IDC_QUESTSTAGE                  1025
#define IDC_CONSTITUTION                1026
#define IDC_SLOTCOLOR3                  1026
#define IDC_PAYPLATINUM                 1026
#define IDC_CHARISMA                    1027
#define IDC_SLOTCOLOR4                  1027
#define IDC_INTELLIGENCE                1028
#define IDC_SLOTCOLOR5                  1028
#define IDC_FIGHTER                     1029
#define IDC_SLOTCOLOR6                  1029
#define IDC_STRENGTHBONUS               1029
#define IDC_CLERIC                      1030
#define IDC_SLOTCOLOR7                  1030
#define IDC_RANGER                      1031
#define IDC_SLOTCOLOR8                  1031
#define IDC_PALADIN                     1032
#define IDC_SLOTCOLOR9                  1032
#define IDC_THIEF                       1033
#define IDC_SLOTCOLOR10                 1033
#define IDC_MAGICUSER                   1034
#define IDC_SLOTCOLOR11                 1034
#define IDC_SLOTCOLOR12                 1035
#define IDC_SLOTCOLOR13                 1036
#define IDC_SLOTCOLOR14                 1037
#define IDC_SLOTCOLOR15                 1038
#define IDC_SLOTCOLOR16                 1039
#define IDC_CHANGEWALL                  1040
#define IDC_CHARACTERNAME               1041
#define IDC_CHANGEDOOR                  1041
#define IDC_CHANGEOVERLAY               1042
#define IDC_OPEN_BLK                    1043
#define IDC_OPENSECRET_BLK              1044
#define IDC_BLOCKED_BLK                 1045
#define IDC_FALSEDOOR_BLK               1046
#define IDC_LOCKED_BLK                  1047
#define IDC_LEVEL                       1048
#define IDC_LOCKEDSECRET_BLK            1048
#define IDC_HITPOINTS                   1049
#define IDC_LOCKEDWIZARD_BLK            1049
#define IDC_LOCKEDWIZARDSECRET_BLK      1050
#define IDC_LOCKEDKEY1                  1051
#define IDC_LOCKEDKEY2                  1052
#define IDC_WALLSLOTCOLOR               1052
#define IDC_LOCKEDKEY3                  1053
#define IDC_OBCOLOR                     1053
#define IDC_LOCKEDKEY4                  1054
#define IDC_WALLSLOTPIC                 1054
#define IDC_LOCKEDKEY5                  1055
#define IDC_COLOR1                      1055
#define IDC_LOCKEDKEY6                  1056
#define IDC_OBTEXT                      1056
#define IDC_LOCKEDKEY7                  1057
#define IDC_ModeText                    1057
#define IDC_LOCKEDKEY8                  1058
#define IDC_BGCOLOR                     1058
#define IDC_OBCOLOR1                    1059
#define IDC_BGPIC                       1059
#define IDC_OBCOLOR2                    1060
#define IDC_ZONECOLOR                   1060
#define IDC_OBCOLOR3                    1061
#define IDC_ZONETEXT                    1061
#define IDC_FORCEEXIT                   1062
#define IDC_OBCOLOR4                    1062
#define IDC_COLOROPENBLK                1062
#define IDC_OBCOLOR5                    1063
#define IDC_OBCOLOR6                    1064
#define IDC_CURRX                       1064
#define IDC_OBCOLOR7                    1065
#define IDC_CURRY                       1065
#define IDC_OBCOLOR8                    1066
#define IDC_COLOR2                      1066
#define IDC_OBCOLOR9                    1067
#define IDC_CURRFACING                  1067
#define IDC_OBCOLOR10                   1068
#define IDC_COLOR3                      1068
#define IDC_OBCOLOR11                   1069
#define IDC_COLOR4                      1069
#define IDC_OBCOLOR12                   1070
#define IDC_COLOR5                      1070
#define IDC_OBCOLOR13                   1071
#define IDC_COLOR6                      1071
#define IDC_OBCOLOR14                   1072
#define IDC_CHANGEBG                    1072
#define IDC_COLOR7                      1072
#define IDC_OBCOLOR15                   1073
#define IDC_CHOOSETEXTEVENTART          1073
#define IDC_COLOR8                      1073
#define IDC_OBCOLOR16                   1074
#define IDC_SMALLPIC                    1074
#define IDC_COLOR9                      1074
#define IDC_BIGPIC                      1075
#define IDC_COLOR10                     1075
#define IDC_NOPIC                       1076
#define IDC_COLOR11                     1076
#define IDC_FORCEBACKUP                 1077
#define IDC_COLOR12                     1077
#define IDC_WAITFORRETURN               1078
#define IDC_COLOR13                     1078
#define IDC_HIGHLIGHTTEXT               1079
#define IDC_COLOR14                     1079
#define IDC_FILENAME                    1080
#define IDC_COLOR15                     1080
#define IDC_COLOR16                     1081
#define IDC_COLORBLOCKBLK               1082
#define IDC_CHOSENLIST                  1093
#define IDC_AVAILLIST                   1094
#define IDC_ADDITEM                     1095
#define IDC_DELETEITEM                  1096
#define IDC_CHOOSE_ITEMS                1096
#define IDC_RETAILER                    1098
#define IDC_DELAY                       1098
#define IDS_HELP_spell_Name             1100
#define IDC_RENAMELEVEL                 1101
#define IDS_HELP_spell_CastingSound     1101
#define IDC_USEBG2                      1102
#define IDS_HELP_spell_School           1102
#define IDC_BGTIMESTART                 1103
#define IDS_HELP_spell_FriendlyFire     1103
#define IDC_BARKEEP                     1104
#define IDC_BGENDTIME                   1104
#define IDS_HELP_spell_CombatOnly       1104
#define IDS_HELP_spell_InCamp           1104
#define IDC_LEVELLIST                   1105
#define IDS_HELP_spell_SaveVersus       1105
#define IDC_TRAINER                     1106
#define IDC_DELETELEVEL                 1106
#define IDS_HELP_spell_MissileArt       1106
#define IDS_HELP_spell_TargCoverArt     1107
#define IDC_ADDSPELL                    1108
#define IDS_HELP_spell_TargHitArt       1108
#define IDC_DELETESPELL                 1109
#define IDS_HELP_spell_SaveResult       1109
#define IDS_HELP_spell_SpecialAbility   1110
#define IDS_HELP_spell_TargetingType    1111
#define IDS_HELP_spell_DurationUnits    1112
#define IDS_HELP_spell_Level            1113
#define IDS_HELP_spell_CastingTime      1114
#define IDS_HELP_spell_NumberOfTargets  1115
#define IDS_HELP_spell_TargetQuantity   1115
#define IDC_CHARITEMS                   1116
#define IDS_HELP_spell_Duration         1116
#define IDC_EVENTTRIGGER                1117
#define IDS_HELP_spell_TargetRange      1117
#define IDC_CHAINTRIGGER                1118
#define IDS_HELP_spell_AttackBonus      1118
#define IDC_ONCEONLY                    1119
#define IDC_DESIGNNAME                  1119
#define IDS_HELP_spell_Damage           1119
#define IDC_CHOOSEFACING                1120
#define IDC_FACENORTH                   1120
#define IDC_LEVELNAME                   1120
#define IDS_HELP_spell_ProtectionBonus  1120
#define IDC_CHOOSERACE                  1121
#define IDC_FACEEAST                    1121
#define IDS_HELP_spell_Healing          1121
#define IDC_CHOOSECLASS                 1122
#define IDC_FACESOUTH                   1122
#define IDS_HELP_spell_Price            1122
#define IDC_FACEWEST                    1123
#define IDS_HELP_spell_TargLingerArt    1123
#define IDC_TRIGGERITEM                 1124
#define IDC_STARTLEVEL                  1124
#define IDS_HELP_spell_Cumulative       1124
#define IDC_QUESTTRIGGER                1125
#define IDC_STARTX                      1125
#define IDS_HELP_spell_UsableByParty    1125
#define IDS_HELP_spell_CanMemorize      1125
#define IDC_EVENT_TYPE                  1126
#define IDC_STARTY                      1126
#define IDS_HELP_spell_CanScribe        1126
#define IDS_HELP_spell_AllowScribe      1126
#define IDC_STARTTIME                   1127
#define IDS_HELP_spell_CastingTimeUnits 1127
#define IDC_STARTEXP                    1128
#define IDS_HELP_spell_CastMsg          1128
#define IDC_STARTEQUIP                  1129
#define IDS_HELP_spell_CoverageSound    1129
#define IDC_STARTPLATINUM               1130
#define IDS_HELP_spell_HitSound         1130
#define IDC_STARTGEMS                   1131
#define IDS_HELP_spell_LingerSound      1131
#define IDC_STARTJEWELRY                1132
#define IDS_HELP_spell_CastArt          1132
#define IDS_HELP_spell_MissileSound     1133
#define IDC_DELETEEVENT                 1134
#define IDS_HELP_spell_Lingers          1134
#define IDC_SEECHAR                     1135
#define IDS_HELP_spell_LingerAffectsOnce 1135
#define IDC_DISTANCE                    1136
#define IDC_SELECTFRAME                 1136
#define IDS_HELP_spell_TargetDuration   1136
#define IDC_ADDCHAR                     1137
#define IDC_SELECTHBORDER               1137
#define IDS_HELP_spell_SpellSavingThrowFailedScript 1137
#define IDC_CAMPART                     1138
#define IDC_DESIGNLIST                  1138
#define IDC_SELECTVBORDER               1138
#define IDS_HELP_spell_SpellSavingThrowSucceededScript 1138
#define IDC_BACKUP                      1139
#define IDC_SELECTCOMBATCOMMON          1139
#define IDS_HELP_spell_CastByClass      1139
#define IDC_SEEMONSTER                  1140
#define IDC_SELECTCOMBATHBORDER         1140
#define IDC_SELECTCOMBATVBORDER         1141
#define IDC_DIRECTION                   1143
#define IDC_SURPRISE                    1144
#define IDC_ScrollPicture               1144
#define IDC_CHOOSEMONSTERS              1145
#define IDC_VERTSCROLLPIC               1145
#define IDC_NOTREASURE                  1146
#define IDC_HORZSCROLLPIC               1146
#define IDC_PARTYNEVERDIES              1147
#define IDC_SELECTFILE                  1147
#define IDC_MAGICNOTWORK                1148
#define IDC_PICFILENAME                 1148
#define IDC_TURNUNDEAD                  1149
#define IDC_AUTOAPPROACH                1150
#define IDS_HELP_spell_DupName          1150
#define IDC_OUTDOORS                    1151
#define IDS_HELP_spell_SpellEffect      1151
#define IDC_CHOOSEITEMS                 1152
#define IDS_HELP_spell_SpellAttribute   1152
#define IDC_SEEART                      1153
#define IDS_HELP_spell_SpellBeginScript 1153
#define IDS_HELP_spell_SpellEndScript   1154
#define IDC_SELECTDEFAULT               1155
#define IDS_HELP_spell_SpellActivateScript 1155
#define IDC_NBRDICE                     1156
#define IDC_SELECTALT                   1156
#define IDS_HELP_spell_SpellModifyScript 1156
#define IDC_NBRSIDES                    1157
#define IDS_HELP_spell_SpellSavingThrowScript 1157
#define IDC_DMGBONUS                    1158
#define IDS_HELP_spell_CanBeDispelled   1158
#define IDC_SAVEEFFECT                  1159
#define IDS_HELP_spell_AutoScribe       1159
#define IDC_SAVEVS                      1160
#define IDS_HELP_spell_CampOnly         1160
#define IDS_HELP_spell_InCombat         1160
#define IDC_ATTACKTHAC0                 1161
#define IDS_HELP_spell_Key              1161
#define IDC_SAVINGTHROWBONUS            1162
#define IDS_HELP_spell_TargetWidth      1162
#define IDC_NBRATTACKS                  1163
#define IDS_HELP_spell_TargetHeight     1163
#define IDC_WHO                         1164
#define IDS_HELP_spell_TargetLength     1164
#define IDC_CHANCE                      1165
#define IDS_HELP_spell_TargetRadius     1165
#define IDS_HELP_spell_TargetNumber     1166
#define IDS_HELP_spell_TargetFriend     1167
#define IDS_HELP_spell_TargetEnemy      1168
#define IDS_HELP_spell_Priority         1169
#define IDC_MONSTERSPEED                1170
#define IDC_DEFAULTFILENAME             1170
#define IDS_HELP_spell_SavingThrowScript 1170
#define IDC_ALTFILENAME                 1171
#define IDS_HELP_spell_SavingThrowFailedScript 1171
#define IDC_ZONENUMBER                  1172
#define IDS_HELP_spell_SavingThrowSucceededScript 1172
#define IDC_ZONESPIN                    1173
#define IDS_HELP_spell_SpellInitiationScript 1173
#define IDC_RANGEZERO                   1174
#define IDC_ZONENAME                    1174
#define IDS_HELP_spell_SpellTerminationScript 1174
#define IDC_BUTTONCHOICES               1175
#define IDC_ALLOWAREAMAP                1175
#define IDC_ITEMLIST                    1176
#define IDC_TURNINGDIFFICULTY           1176
#define IDC_ITEM1                       1177
#define IDC_SUMMONEDMONSTER             1177
#define IDC_ITEM3                       1178
#define IDC_INDOORCOMBAT                1178
#define IDC_ITEM2                       1179
#define IDC_OUTDOORCOMBAT               1179
#define IDC_ITEM4                       1180
#define IDC_ITEM5                       1181
#define IDC_TREASUREART                 1181
#define IDC_ITEM6                       1182
#define IDC_ITEM7                       1183
#define IDC_ITEM8                       1184
#define IDC_IDENTIFIED1                 1186
#define IDC_IDENTIFIED2                 1187
#define IDC_LABEL1                      1187
#define IDC_IDENTIFIED3                 1188
#define IDC_PRESENT1                    1188
#define IDC_IDENTIFIED4                 1189
#define IDC_UPCLOSE1                    1189
#define IDC_IDENTIFIED5                 1190
#define IDC_PICLIST                     1190
#define IDC_IDENTIFIED6                 1191
#define IDC_LOADPIC                     1191
#define IDC_IDENTIFIED7                 1192
#define IDC_VIEWPIC                     1192
#define IDC_IDENTIFIED8                 1193
#define IDC_LABEL2                      1193
#define IDC_DELETEPIC                   1193
#define IDC_BUTTONOPTION1               1194
#define IDC_NAME                        1194
#define IDC_PRESENT2                    1195
#define IDC_UPCLOSE2                    1196
#define IDC_DRUIDCHECK                  1198
#define IDC_BUTTONOPTION2               1200
#define IDS_HELP_item_Name              1200
#define IDC_LABEL3                      1201
#define IDS_HELP_item_IDname            1201
#define IDC_PRESENT3                    1202
#define IDS_HELP_item_ROFperRound       1202
#define IDC_UPCLOSE3                    1203
#define IDS_HELP_item_SpellEffect       1203
#define IDS_HELP_item_SpellLevel        1204
#define IDC_CURSED                      1205
#define IDS_HELP_item_SpellClass        1205
#define IDC_USABLE                      1206
#define IDS_HELP_item_Cost              1206
#define IDC_BUTTONOPTION3               1207
#define IDC_COST                        1207
#define IDS_HELP_item_HandsToUse        1207
#define IDC_NotMagical                  1207
#define IDC_LABEL4                      1208
#define IDC_ENCUMBRANCE                 1208
#define IDS_HELP_item_Class             1208
#define IDS_HELP_item_Baseclass         1208
#define IDC_PRESENT4                    1209
#define IDC_BUNDLEQTY                   1209
#define IDS_HELP_item_Range             1209
#define IDC_UPCLOSE4                    1210
#define IDC_EXPPTS                      1210
#define IDS_HELP_item_SmallDamageDice   1210
#define IDS_HELP_item_ACbase            1211
#define IDC_LOCATIONCARRIED             1212
#define IDS_HELP_item_ACbonus           1212
#define IDC_HANDSNEEDED                 1213
#define IDS_HELP_item_LargeDamageDice   1213
#define IDC_BUTTONOPTION4               1214
#define IDC_PROTECTIONBASE              1214
#define IDS_HELP_item_Experience        1214
#define IDC_LABEL5                      1215
#define IDC_WPNTYPE                     1215
#define IDS_HELP_item_Encumbrance       1215
#define IDC_PRESENT5                    1216
#define IDC_ROF_PER_RND                 1216
#define IDS_HELP_item_AttackBonus       1216
#define IDC_UPCLOSE5                    1217
#define IDC_RANGE                       1217
#define IDS_HELP_item_Cursed            1217
#define IDC_DMG_DICE_SM                 1218
#define IDS_HELP_item_LocationCarried   1218
#define IDS_HELP_item_ReadiedLocation   1218
#define IDC_NBR_DICE_SM                 1219
#define IDS_HELP_item_BundleQuantity    1219
#define IDC_DMG_BONUS_SM                1220
#define IDS_HELP_item_SpecialAbilities  1220
#define IDS_HELP_item_SpecialAbility    1220
#define IDC_BUTTONOPTION5               1221
#define IDC_DMG_DICE_LG                 1221
#define IDS_HELP_item_WeaponType        1221
#define IDC_NBR_DICE_LG                 1222
#define IDS_HELP_item_Usable            1222
#define IDC_DMG_BONUS_LG                1223
#define IDS_HELP_item_NumberCharges     1223
#define IDC_MAGICALPROPERTIES           1224
#define IDS_HELP_item_SpriteData        1224
#define IDC_ATTACKBONUS                 1225
#define IDS_HELP_item_HitSound          1225
#define IDC_AMMOTYPE                    1225
#define IDC_PROTECTIONBONUS             1226
#define IDS_HELP_item_MissSound         1226
#define IDS_HELP_item_LaunchSound       1227
#define IDS_HELP_item_Scribable         1228
#define IDC_IDENTIFIEDNAME              1229
#define IDS_HELP_item_Droppable         1229
#define IDC_NUMCHARGES                  1230
#define IDC_CHOOSESPELL                 1231
#define IDC_SPELLLEVEL                  1232
#define IDC_CHOOSESPELLS                1236
#define IDC_CHOOSEICON                  1238
#define IDC_CHOOSESPIC                  1240
#define IDC_MONSTER1                    1241
#define IDC_CHOOSE_SP_ATTACKS           1241
#define IDC_MONSTER2                    1242
#define IDC_MONSTER3                    1243
#define IDC_MONSTER4                    1244
#define IDC_MONSTER5                    1245
#define IDC_MONSTER6                    1246
#define IDC_ARMORCLASS                  1247
#define IDC_ADDMONSTER                  1248
#define IDC_MOVEMENT                    1248
#define IDC_DELETEMONSTER               1249
#define IDC_HITDICE                     1249
#define IDC_NUMMONSTERS1                1250
#define IDC_HITDICEBONUS                1250
#define IDS_HELP_item_DupName           1250
#define IDC_NUMMONSTERS2                1251
#define IDC_THAC0                       1251
#define IDS_HELP_item_Key               1251
#define IDC_NUMMONSTERS3                1252
#define IDS_HELP_item_ASL               1252
#define IDC_NUMMONSTERS4                1253
#define IDC_ATTACKDICE                  1253
#define IDS_HELP_item_CanHalveJoin      1253
#define IDC_NUMMONSTERS5                1254
#define IDC_ATTACKNBRDICE               1254
#define IDS_HELP_item_ExamineEvent      1254
#define IDC_NUMMONSTERS6                1255
#define IDC_DMGDICE                     1255
#define IDS_HELP_item_ExamineLabel      1255
#define IDC_FRIENDLY1                   1256
#define IDC_MAGICRESISTANCE             1256
#define IDC_DMGNBRDICE                  1256
#define IDS_HELP_item_NotMagical        1256
#define IDC_FRIENDLY2                   1257
#define IDC_HEALDICE                    1257
#define IDC_FRIENDLY3                   1258
#define IDC_HEALNBRDICE                 1258
#define IDC_MONSTERSIZE                 1258
#define IDC_FRIENDLY4                   1259
#define IDC_TARGDICE                    1259
#define IDC_MONSTERCLASS                1259
#define IDC_FRIENDLY5                   1260
#define IDC_XPVALUE                     1260
#define IDC_TARGNBRDICE                 1260
#define IDC_FRIENDLY6                   1261
#define IDC_RANGEDICE                   1261
#define IDC_CHOOSEART                   1262
#define IDC_RANGENBRDICE                1262
#define IDC_DURATIONDICE                1263
#define IDC_PASSWORD                    1264
#define IDC_DURATIONNBRDICE             1264
#define IDC_NBRTRIES                    1265
#define IDC_ALLOWEDINCAMP               1266
#define IDC_FRIENDLYFIREOK              1267
#define IDC_FACING                      1268
#define IDC_PROTDICE                    1268
#define IDC_ENEMYFIREOK                 1268
#define IDC_SUCCESSTEXT                 1269
#define IDC_PROTNBRDICE                 1269
#define IDC_EXECUTEEVENT                1270
#define IDC_PROTDICEBONUS               1270
#define IDC_SUCCESSACTION               1271
#define IDC_PROTBONUSLEVEL              1271
#define IDC_PROTMAX                     1272
#define IDC_FAILTEXT                    1273
#define IDC_HEAR                        1273
#define IDC_TARGETINGTYPE               1273
#define IDC_FAILACTION                  1274
#define IDC_SEE                         1274
#define IDC_ATTACKDICEBONUS             1275
#define IDC_ATTACKBONUSLEVEL            1276
#define IDC_EXPBONUS                    1277
#define IDC_ATTACKMAX                   1277
#define IDC_STARTLOC                    1278
#define IDC_DMGDICEBONUS                1278
#define IDC_COL                         1279
#define IDC_DMGBONUSLEVEL               1279
#define IDC_ROW                         1280
#define IDC_DMGMAX                      1280
#define IDC_HEALDICEBONUS               1281
#define IDC_TOURSTEP                    1282
#define IDC_HEALBONUSLEVEL              1282
#define IDC_SPINSTEP                    1283
#define IDC_HEALMAX                     1283
#define IDC_STEPTAKEN                   1284
#define IDC_TARGDICEBONUS               1284
#define IDC_STEPTEXT                    1285
#define IDC_TARGBONUSLEVEL              1285
#define IDC_TARGMAX                     1286
#define IDC_RANGEDICEBONUS              1287
#define IDC_ART                         1288
#define IDC_RANGEBONUSLEVEL             1288
#define IDC_RANGEMAX                    1289
#define IDC_SOUND                       1290
#define IDC_CLASS                       1290
#define IDC_NPCSAYS                     1291
#define IDC_DURATIONDICEBONUS           1291
#define IDC_CASTTIME                    1292
#define IDC_DURATIONBONUSLEVEL          1293
#define IDC_REMOVECHAR                  1295
#define IDC_ITEMS1                      1296
#define IDC_SAVERESULT                  1296
#define IDC_ITEMS2                      1297
#define IDC_DURATIONRATE                1297
#define IDC_ITEMS3                      1298
#define IDC_DURATIONMAX                 1298
#define IDC_ITEMS4                      1299
#define IDC_ITEMS5                      1300
#define IDC_ICONPICTURE                 1300
#define IDC_SmallPicture2               1300
#define IDS_HELP_monster_Name           1300
#define IDC_ITEMS6                      1301
#define IDC_CHARSPIC                    1301
#define IDS_HELP_monster_IconFile       1301
#define IDC_CHARICONPIC                 1302
#define IDS_HELP_monster_MissSound      1302
#define IDC_CONVERTITEMDB               1303
#define IDS_HELP_monster_HitSound       1303
#define IDC_CONVERTMONSTERDB            1304
#define IDS_HELP_monster_Intelligence   1304
#define IDC_CONVERTSPELLDB              1305
#define IDS_HELP_monster_ArmorClass     1305
#define IDC_3DPicture                   1306
#define IDS_HELP_monster_MovementRate   1306
#define IDC_CONVERTCLASSDB              1306
#define IDS_HELP_monster_HitDice        1307
#define IDC_CONVERTBASECLASSDB          1307
#define IDS_HELP_monster_HitDiceBonus   1308
#define IDC_CONVERTRACEDB               1308
#define IDC_LOADDEFITEMS                1309
#define IDS_HELP_monster_THAC0          1309
#define IDC_LOADDEFMONSTERS             1310
#define IDS_HELP_monster_NbrAttacks     1310
#define IDC_LOADDEFSPELLS               1311
#define IDS_HELP_monster_AttackDice     1311
#define IDS_HELP_monster_Attack         1311
#define IDC_ITEMSIZE                    1312
#define IDS_HELP_monster_MagicResistance 1312
#define IDC_BGPicture                   1313
#define IDC_SPELLSIZE                   1313
#define IDS_HELP_monster_Size           1313
#define IDC_EXPORTITEMDB                1314
#define IDS_HELP_monster_Morale         1314
#define IDC_WallPicture                 1315
#define IDC_EXPORTMONSTERDB             1315
#define IDS_HELP_monster_XPValue        1315
#define IDC_BGPicture2                  1316
#define IDC_ISPREGEN                    1316
#define IDC_EXPORTSPELLDB               1316
#define IDS_HELP_monster_SpecialAbility 1316
#define IDS_HELP_monster_Classes        1317
#define IDC_CLASSSIZE                   1317
#define IDS_HELP_monster_Form           1318
#define IDC_BASECLASSSIZE               1318
#define IDC_CHOOSEALIGNMENT             1319
#define IDS_HELP_monster_Penalty        1319
#define IDC_RACESIZE                    1319
#define IDC_CHOOSEGENDER                1320
#define IDS_HELP_monster_Immunity       1320
#define IDC_CONVERTABILITYDB            1320
#define IDC_CONVERTABILITY              1320
#define IDC_LEVEL1                      1321
#define IDS_HELP_monster_MiscOptions    1321
#define IDC_ABILITYSIZE                 1321
#define IDC_PREVIEW                     1322
#define IDC_LEVEL2                      1322
#define IDS_HELP_monster_MoveSound      1322
#define IDC_EXPORTSPECABDB              1322
#define IDC_IMAGE                       1323
#define IDC_LEVEL3                      1323
#define IDS_HELP_monster_DeathSound     1323
#define IDC_CLASSSIZE2                  1323
#define IDC_SPECABSIZE                  1323
#define IDC_L1CLASS                     1324
#define IDS_HELP_item_HitSpriteData     1324
#define IDC_IMPORTSPECABDB              1324
#define IDC_L2CLASS                     1325
#define IDS_HELP_item_NonLethal         1325
#define IDC_EXPORTBASECLASSDB           1325
#define IDC_L3CLASS                     1326
#define IDS_HELP_item_AmmoType          1326
#define IDC_EXPORTCLASSDB               1326
#define IDC_CHARCLASSTEXT               1327
#define IDS_HELP_item_RechargeRate      1327
#define IDC_EXPORTRACEDB                1327
#define IDS_HELP_monster_Item           1328
#define IDC_EXPORTABILITY               1328
#define IDS_HELP_monster_UndeadType     1329
#define IDS_HELP_monster_UndeadLevel    1329
#define IDC_ImportGlobalSettings        1329
#define IDS_HELP_monster_UseHitDice     1330
#define IDC_ImportCharacters            1330
#define IDS_HELP_monster_Key            1331
#define IDS_HELP_monster_Race           1332
#define IDC_ExportGlobalSettings        1332
#define IDC_EPCOLOR1                    1333
#define IDC_ExportCharacters            1333
#define IDC_EPCOLOR2                    1334
#define IDC_EPCOLOR3                    1335
#define IDC_EPCOLOR4                    1336
#define IDC_EPCOLOR5                    1337
#define IDC_EPCOLOR6                    1338
#define IDC_EPCOLOR7                    1339
#define IDC_EPCOLOR8                    1340
#define IDC_EPX1                        1341
#define IDC_EPX2                        1342
#define IDC_EPX3                        1343
#define IDC_EPX4                        1344
#define IDC_EPX5                        1345
#define IDC_EPX6                        1346
#define IDC_EPX7                        1347
#define IDC_EPX8                        1348
#define IDC_EPY1                        1349
#define IDC_EPY2                        1350
#define IDS_HELP_monster_DupName        1350
#define IDC_EPY3                        1351
#define IDS_HELP_monster_Class          1351
#define IDC_EPY4                        1352
#define IDC_EPY5                        1353
#define IDC_EPY6                        1354
#define IDC_EPY7                        1355
#define IDC_EPY8                        1356
#define IDC_SELECT1                     1360
#define IDC_BLOCKAGEOPEN                1361
#define IDC_BLOCKAGEBLK                 1362
#define IDC_MAX_X                       1363
#define IDC_MAX_Y                       1364
#define IDC_QUESTIONTEXT                1364
#define IDC_TRANSFERTEXT                1365
#define IDC_ASKYESNOQ                   1366
#define IDC_SELECT2                     1367
#define IDC_YESTRANSFER                 1367
#define IDC_SELECT3                     1368
#define IDC_NOTRANSFER                  1368
#define IDC_SELECT4                     1369
#define IDC_SELECT5                     1370
#define IDC_ENTRYPOINTLIST              1370
#define IDC_SELECT6                     1371
#define IDC_LEVELSPIN                   1371
#define IDC_SELECT7                     1372
#define IDC_LEVELNUM                    1372
#define IDC_SELECT8                     1373
#define IDC_SELECT9                     1374
#define IDC_ALLOWAUTOMAP                1374
#define IDC_SELECT10                    1375
#define IDC_NOMAP                       1375
#define IDC_SELECT11                    1376
#define IDC_DESTROYDROW                 1376
#define IDC_SELECT12                    1377
#define IDC_ATTEMPTSENTRY               1377
#define IDC_SELECT13                    1378
#define IDC_AFTERENTRY                  1378
#define IDC_SELECT14                    1379
#define IDC_DELETESLOT                  1379
#define IDC_SELECT15                    1380
#define IDC_SELECT16                    1381
#define IDC_DUNGEON                     1381
#define IDC_OVERLAND                    1382
#define IDC_USEDEFBG                    1383
#define IDC_COPYLEVEL                   1386
#define IDC_ZONEMSG                     1387
#define IDC_PASTELEVEL                  1387
#define IDC_SPRITEPIC                   1388
#define IDC_PICWIDTH                    1390
#define IDC_PICHEIGHT                   1391
#define IDC_EVENTCHANCE                 1394
#define IDC_EVENTMINUTES                1395
#define IDC_CANTREST                    1396
#define IDC_StepEventName               1397
#define IDC_STEPCOUNT                   1399
#define IDS_HELP_WallEditor             1400
#define IDC_ZONE1                       1401
#define IDS_HELP_DBUtils                1401
#define IDC_ZONE2                       1402
#define IDS_HELP_LogicBlock             1402
#define IDC_ZONE3                       1403
#define IDS_HELP_MapStyle               1403
#define IDC_ZONE4                       1404
#define IDS_HELP_ability_SpecialAbility 1404
#define IDC_ZONE5                       1405
#define IDC_ZONE6                       1406
#define IDC_ZONE7                       1407
#define IDC_ZONE8                       1408
#define IDC_STEPEVENT_NUM               1409
#define IDC_STEPEVENTSPIN               1410
#define IDC_SHOPENTERTEXT               1411
#define IDC_ZONE9                       1411
#define IDC_ENTERTEXT                   1412
#define IDC_ZONE10                      1412
#define IDC_ZONE11                      1413
#define IDC_ZONE12                      1414
#define IDC_MUSTHITRETURN               1415
#define IDC_ZONE13                      1415
#define IDC_ZONE14                      1416
#define IDC_ROLLSTATS                   1417
#define IDC_ZONE15                      1417
#define IDC_MONEY                       1418
#define IDC_ZONE16                      1418
#define IDC_MF_MAMMAL                   1419
#define IDC_MF_ANIMAL                   1420
#define IDC_MF_SNAKE                    1421
#define IDC_TELEPORT                    1421
#define IDC_SUCCESSTELEPORT             1421
#define IDC_MF_GIANT                    1422
#define IDC_FAILTELEPORT                1422
#define IDC_MF_LARGE                    1423
#define IDC_SUCCESSIMPOSSIBLE           1423
#define IDC_MI_POISON                   1424
#define IDC_MI_DEATH                    1425
#define IDC_PAYGEMS                     1425
#define IDC_MI_CONFUSION                1426
#define IDC_MI_VORPAL                   1427
#define IDC_ALWAYSSUCCEEDS              1428
#define IDC_MF_UNDEAD                   1428
#define IDC_MP_DWAC                     1429
#define IDC_ALWAYSFAILS                 1429
#define IDC_MP_GNAC                     1430
#define IDC_CHECKSTR                    1430
#define IDC_MP_DWTHAC0                  1431
#define IDC_CHECKINT                    1431
#define IDC_MP_GNTHAC0                  1432
#define IDC_CHECKWIS                    1432
#define IDC_MP_RANGDMG                  1433
#define IDC_CHECKDEX                    1433
#define IDC_MO_HELDCHARM                1434
#define IDC_CHECKCON                    1434
#define IDC_MO_AFFBYDISPEVIL            1435
#define IDC_CHECKCHARISMA               1435
#define IDC_CHECKSTRBONUS               1436
#define IDC_CHECKPP                     1437
#define IDC_CHECKOL                     1438
#define IDC_CHECKFT                     1439
#define IDC_CHECKMS                     1440
#define IDC_CHECKHS                     1441
#define IDC_CHECKHN                     1442
#define IDC_CHECKCW                     1443
#define IDC_CHECKRL                     1444
#define IDC_COMPARETODIE                1447
#define IDC_MUSTHAVE                    1448
#define IDC_DIESIDES                    1449
#define IDC_NUMTRIES                    1450
#define IDC_GIVELIST                    1451
#define IDC_TAKELIST                    1452
#define IDC_REMOVEGIVE                  1454
#define IDC_TRIGGERSPECITEM             1455
#define IDC_REMOVETAKE                  1456
#define IDC_TRIGGERSPECKEY              1456
#define IDC_PASSDAYS                    1456
#define IDC_GIVEKEY                     1457
#define IDC_PASSHOURS                   1457
#define IDC_ATTRIBUTES                  1457
#define IDC_TAKEKEY                     1458
#define IDC_PASSMINUTES                 1458
#define IDC_YESTEXT                     1460
#define IDC_NOTEXT                      1461
#define IDC_YESCHAINOPTION              1462
#define IDC_NOCHAINOPTION               1463
#define IDC_ALLOWFIGHTS                 1466
#define IDC_DRINK_NUM                   1468
#define IDC_DRINKSPIN                   1469
#define IDC_DRINKNAME                   1470
#define IDC_DRINKPOINTS                 1471
#define IDC_POINTTRIGGER                1472
#define IDC_TALE_NUM                    1474
#define IDC_TALESPIN                    1475
#define IDC_TALETEXT                    1476
#define IDC_ALLOWDRINKS                 1477
#define IDC_TALEORDER                   1478
#define IDC_TALESRANDOM                 1479
#define IDC_MAXLEVEL                    1480
#define IDC_SPELLLIST                   1481
#define IDC_COSTFACTOR                  1482
#define IDC_ALLOWDONATIONS              1483
#define IDC_DONATETRIGGER               1484
#define IDC_EVENTTREE                   1487
#define IDC_EDITEVENT                   1488
#define IDC_INSERTEVENT                 1492
#define IDC_CONFIGZONES                 1495
#define IDC_CONFIGSTEPEVENTS            1496
#define IDC_MAGICUSERS                  1499
#define IDC_CLERICS                     1500
#define IDC_FIGHTERS                    1501
#define IDC_RANGERS                     1502
#define IDC_PALADINS                    1503
#define IDC_DRUIDS                      1504
#define IDC_THIEFS                      1505
#define IDC_TRAINCOST                   1506
#define IDC_TOWNART                     1507
#define IDC_LEVELSIZE                   1512
#define IDC_LIST                        1513
#define IDC_DELETE                      1517
#define IDC_ADD                         1518
#define IDC_SPECIALITEM                 1519
#define IDC_SPECIALKEY                  1520
#define IDC_QUEST                       1521
#define IDC_EDIT                        1523
#define IDC_QUESTSELECT                 1526
#define IDC_STAGE                       1527
#define IDC_COMPLETEONACCEPT            1530
#define IDC_FAILONREJECT                1531
#define IDC_ACCEPT                      1532
#define IDC_QTY                         1533
#define IDC_VAROPERATION                1534
#define IDC_OBJECTSELECT                1535
#define IDC_ENDPLAY                     1536
#define IDC_ITEMCHECK                   1537
#define IDC_RESULTSELECT                1539
#define IDC_FILEBROWSE                  1545
#define IDC_PLAY                        1550
#define IDC_STOP                        1551
#define IDC_SOUNDS                      1551
#define IDC_PARTYSTEP                   1552
#define IDC_PARTYBUMP                   1553
#define IDC_INTROMUSIC                  1554
#define IDC_DEATHMUSIC                  1555
#define IDC_SOUNDSELECT                 1556
#define IDC_CHARHIT                     1556
#define IDC_CHARMISS                    1557
#define IDC_CREDITSMUSIC                1558
#define IDC_REMOVE                      1559
#define IDC_LOOP                        1560
#define IDC_SOUNDLIST                   1561
#define IDC_FILETYPESALLOWED            1562
#define IDC_SPELLSOUND                  1564
#define IDC_INROUTEANIM                 1565
#define IDC_CASTCOST                    1566
#define IDC_TARGCOVANIM                 1567
#define IDC_HITANIM                     1568
#define IDC_LINGERANIM                  1569
#define IDC_CASTANIM                    1570
#define IDC_COVERAGESOUND               1571
#define IDC_SPELLHITSOUND               1572
#define IDC_SPELLLINGERSOUND            1573
#define IDC_PRIORITY                    1574
#define IDC_IDNAME                      1577
#define IDC_HITSOUND                    1580
#define IDC_MISSSOUND                   1581
#define IDC_LAUNCHSOUND                 1582
#define IDC_FONTSELECT                  1584
#define IDC_DEATHSOUND                  1585
#define IDC_MOVESOUND                   1586
#define IDC_SPECABLIST                  1589
#define IDC_ADDSPECAB                   1590
#define IDC_DELETESPECAB                1591
#define IDC_DELETELine                  1591
#define IDC_SPECABCOMBO                 1592
#define IDC_SPECABS                     1593
#define IDC_RenameSpecAbility           1593
#define IDC_EDITSPELL                   1599
#define IDC_EDITITEM                    1601
#define IDC_RESTARTFRAME                1602
#define IDC_MAP_SCROLL_PIC              1607
#define IDC_HORZ_SCROLL                 1608
#define IDC_VERT_SCROLL                 1609
#define IDC_WALLSLOT                    1610
#define IDC_BACKDROPSLOT                1611
#define IDC_CLEARLEVEL                  1612
#define IDC_MAPNAME                     1613
#define IDC_UNLOCKSPELL                 1614
#define IDC_FWIDTH                      1615
#define IDC_FHEIGHT                     1616
#define IDC_NUMFRAMES                   1617
#define IDC_VIEWALLPIC                  1618
#define IDC_UPDATESTATS                 1619
#define IDC_TOGGLEANIM                  1620
#define IDC_NEXTFRAME                   1621
#define IDC_COMBATDEATH                 1622
#define IDC_COMBATDYING                 1623
#define IDC_UpdateVersion               1624
#define IDC_VersionText                 1625
#define IDC_MISSILEART                  1626
#define IDC_ANIMATIONSTYLE              1627
#define IDC_DEFAULTANIM                 1628
#define IDC_RADIUSANIM                  1629
#define IDC_EACHTARGETANIM              1630
#define IDC_DIRECTIONALANIM             1631
#define IDC_OK                          1638
#define IDC_Version                     1639
#define IDC_BLOCK_Type                  1653
#define IDC_CellStatus                  1656
#define IDC_KwikKlik                    1658
#define IDC_CHECK1                      1707
#define IDC_CHECK2                      1708
#define IDC_CHECK3                      1709
#define IDC_CHECK4                      1710
#define IDC_CHECK5                      1711
#define IDC_CHECK6                      1712
#define IDC_CHECK7                      1713
#define IDC_CHECK8                      1714
#define IDC_CHECK9                      1715
#define IDC_CHECK10                     1716
#define IDC_CHECK11                     1717
#define IDC_CHECK12                     1718
#define IDC_CHECK13                     1719
#define IDC_CHECK14                     1720
#define IDC_CHECK15                     1721
#define IDC_CHECK16                     1722
#define IDC_CHECK17                     1723
#define IDC_CHECK18                     1724
#define IDC_CHECK19                     1725
#define IDC_CHECK20                     1726
#define IDC_CHECK21                     1727
#define IDC_CHECK22                     1728
#define IDC_CHECK23                     1729
#define IDC_CHECK24                     1730
#define IDC_CHECK25                     1731
#define IDC_CHECK26                     1732
#define IDC_CHECK27                     1733
#define IDC_CHECK28                     1734
#define IDC_CHECK29                     1735
#define IDC_CHECK30                     1736
#define IDC_CHECK31                     1737
#define IDC_CHECK32                     1738
#define IDC_CHECK33                     1739
#define IDC_CHECK34                     1740
#define IDC_CHECK35                     1741
#define IDC_CHECK36                     1742
#define IDC_CHECK37                     1743
#define IDC_CHECK38                     1744
#define IDC_CHECK39                     1745
#define IDC_CHECK40                     1746
#define IDC_CHECK41                     1747
#define IDC_CHECK42                     1748
#define IDC_CHECK43                     1749
#define IDC_CHECK44                     1750
#define IDC_CHECK45                     1751
#define IDC_CHECK46                     1752
#define IDC_CHECK47                     1753
#define IDC_CHECK48                     1754
#define IDC_Red                         1755
#define IDC_Green                       1756
#define IDC_Blue                        1757
#define IDC_DEFAULT                     1758
#define IDC_ACCESSKEY1                  1759
#define IDC_ACCESSKEY2                  1760
#define IDC_ACCESSKEY3                  1761
#define IDC_ACCESSKEY4                  1762
#define IDC_ACCESSKEY5                  1763
#define IDC_ACCESSKEY6                  1764
#define IDC_ACCESSKEY7                  1765
#define IDC_ACCESSKEY8                  1766
#define IDC_IMPORTFRUAITEMS             1767
#define IDC_IMPORTFRUAMONSTERS          1768
#define IDC_IMPORTFRUASPELLS            1769
#define IDC_IMPORTFRUADESIGN            1770
#define IDC_EDITITEMTEXT                1771
#define IDC_EDITMONSTERTEXT             1772
#define IDC_EDITSPELLTEXT               1773
#define IDC_STARTAGE                    1774
#define IDC_MATCHCOMBO                  1775
#define IDC_MORALE2                     1775
#define IDC_USECASE                     1776
#define IDC_KILLSOUND                   1779
#define IDC_USEVAULT                    1780
#define IDC_TAKEINV                     1781
#define IDC_TAKEMONEY                   1782
#define IDC_TAKEGEMS                    1783
#define IDC_TAKEJEWELRY                 1784
#define IDC_TAKEFROM                    1785
#define IDC_QTYTYPEINV                  1786
#define IDC_QTYTYPEJEWELRY              1787
#define IDC_ITEMQTY                     1788
#define IDC_MONEYQTY                    1789
#define IDC_GEMQTY                      1790
#define IDC_JEWELRYQTY                  1791
#define IDC_QTYTYPEGEMS                 1792
#define IDC_QTYTYPEMONEY                1793
#define IDC_MONEYTYPE                   1795
#define IDC_ALLINFOLDER                 1797
#define IDC_DESTX                       1798
#define IDC_DESTY                       1799
#define IDC_YMAX                        1800
#define IDC_XMAX                        1801
#define IDC_HEALHP                      1802
#define IDC_HEALCURSE                   1803
#define IDC_HEALDRAIN                   1804
#define IDC_HEALWHO                     1805
#define IDC_DELETEALLCHAINED            1806
#define IDC_InputTypeF                  1807
#define IDC_InputTypeB                  1808
#define IDC_InputTypeA                  1809
#define IDC_InputTypeD                  1810
#define IDC_InputTypeG                  1811
#define IDC_InputParamA                 1812
#define IDC_InputParamD                 1813
#define IDC_InputParamG                 1814
#define IDC_InputParamB                 1815
#define IDC_InputParamF                 1816
#define IDC_GateTypeC                   1817
#define IDC_GateTypeE                   1818
#define IDC_GateTypeI                   1819
#define IDC_GateTypeH                   1820
#define IDC_GateTypeJ                   1821
#define IDC_GateTypeK                   1822
#define IDC_GateTypeL                   1823
#define IDC_ActionType2                 1824
#define IDC_ActionType1                 1825
#define IDC_ActionParam1                1826
#define IDC_ActionParam2                1827
#define IDC_NoChain                     1828
#define IDC_AlwaysChain                 1829
#define IDC_ConditionallyChain          1830
#define IDC_NotC                        1831
#define IDC_NotE                        1832
#define IDC_NotH                        1833
#define IDC_NotI                        1834
#define IDC_NotJ                        1835
#define IDC_NotK                        1836
#define IDC_ChainIfFalse                1837
#define IDC_ChainIfTrue                 1838
#define IDC_Debug                       1839
#define IDC_IfTrue_1                    1840
#define IDC_RADIO2                      1841
#define IDC_RADIO3                      1842
#define IDC_IfTrue_2                    1843
#define IDC_RADIO5                      1844
#define IDC_RADIO6                      1845
#define IDC_EXPANDALL                   1846
#define IDC_COLLAPSEALL                 1847
#define IDC_LOADOVERLANDMAP             1848
#define IDC_WIDTHTEXT                   1849
#define IDC_HEIGHTTEXT                  1850
#define IDC_DELETEALL                   1851
#define IDC_IMAGEFORMAT                 1852
#define IDC_CLEAR                       1855
#define IDC_DUNGTIME                    1856
#define IDC_DUNGSEARCHTIME              1857
#define IDC_WILDTIME                    1858
#define IDC_WILDSEARCHTIME              1859
#define IDC_ALLOWCHARCREATE             1863
#define IDC_MINPARTYSIZE                1864
#define IDC_MINPCS                      1864
#define IDC_MAXPARTYSIZE                1865
#define IDC_MAXPCS                      1865
#define IDC_EDITPROPS                   1866
#define IDC_MAXPARTY                    1866
#define IDC_DEADATZEROHP                1867
#define IDC_AVStyleList                 1868
#define IDC_SELECTSOUND                 1870
#define IDC_MAXHEIGHT                   1871
#define IDC_MAXWIDTH                    1872
#define IDC_SLOTTAB                     1874
#define IDC_TOGGLEBGMETHOD              1875
#define IDC_BLENDPCNT                   1876
#define IDC_TOGGLEBGBANDS               1876
#define IDC_USEALPHABLEND               1877
#define IDC_ATTNAME                     1880
#define IDC_CHANGEMADETEXT              1881
#define IDC_CHANGEDELTA                 1882
#define IDC_CHANGEPCNT                  1883
#define IDC_CUMULATIVE                  1884
#define IDC_DURATIONTEXT                1885
#define IDC_DURATIONTEMPORAL            1886
#define IDC_EFFECTDURATIONTEXT          1886
#define IDC_DURATIONPERM                1887
#define IDC_AFFECTSTARGET               1888
#define IDC_AFFECTSTARGETER             1889
#define IDC_USEAUTODARKEN               1890
#define IDC_AUTODARKENAMOUNT            1891
#define IDC_USEOVERLAYBLEND             1892
#define IDC_OVERLAYBLENDAMOUNT          1893
#define IDC_DARKENTIMESTART             1894
#define IDC_DARKENENDTIME               1895
#define IDC_PARAMBSELECT                1897
#define IDC_PARAMFSELECT                1898
#define IDC_ATTLIST                     1898
#define IDC_PARAMASELECT                1899
#define IDC_SCRIPT                      1899
#define IDC_PARAMDSELECT                1900
#define IDC_NUMTARGETTEXT               1900
#define IDC_SCRIPT2                     1900
#define IDC_TARG_P1_TEXT                1900
#define IDC_PARAMGSELECT                1901
#define IDC_TARGETRANGETEXT             1901
#define IDC_SCRIPT3                     1901
#define IDC_TARG_P2_TEXT                1901
#define IDC_ACTION1SELECT2              1902
#define IDC_TARG_P4_TEXT                1902
#define IDC_ATTRIBUTELIST               1903
#define IDC_ACTION2SELECT2              1903
#define IDC_ADDATTRIBUTE                1904
#define IDC_DELETEATTRIBUTE             1905
#define IDC_EDITATTRIBUTE               1906
#define IDC_USETRANSPARENCY             1906
#define IDC_TARG_P5_TEXT                1907
#define IDC_TARG_P3_TEXT                1908
#define IDC_SUPPRESSSTEPSOUND           1909
#define IDC_FRAMES                      1910
#define IDC_UPDATE                      1911
#define IDC_STEPSOUND                   1913
#define IDC_BUMPSOUND                   1914
#define IDC_USABLEBYPLAYER              1915
#define IDC_CANMEMORIZE                 1915
#define IDC_NAME1                       1916
#define IDC_NAME2                       1917
#define IDC_NAME3                       1918
#define IDC_NAME4                       1919
#define IDC_NAME5                       1920
#define IDC_NAME6                       1921
#define IDC_NAME7                       1922
#define IDC_NAME8                       1923
#define IDC_NAME9                       1924
#define IDC_NAME10                      1925
#define IDC_CONVERT1                    1926
#define IDC_CONVERT2                    1927
#define IDC_CONVERT3                    1928
#define IDC_CONVERT4                    1929
#define IDC_CONVERT5                    1930
#define IDC_CONVERT6                    1931
#define IDC_CONVERT7                    1932
#define IDC_CONVERT8                    1933
#define IDC_CONVERT9                    1934
#define IDC_CONVERT10                   1935
#define IDC_ISBASE1                     1936
#define IDC_GEMNAME                     1936
#define IDC_ISBASE2                     1937
#define IDC_CONFIGMONEY                 1937
#define IDC_JEWELRYNAME                 1937
#define IDC_ISBASE3                     1938
#define IDC_SELECTICONBG                1938
#define IDC_ISBASE4                     1939
#define IDC_SELECTTITLE                 1939
#define IDC_SELECTTITLES                1939
#define IDC_ISBASE5                     1940
#define IDC_SCREENBG                    1940
#define IDC_ISBASE6                     1941
#define IDC_ALLOWMAGIC                  1941
#define IDC_CREDITS                     1941
#define IDC_ISBASE7                     1942
#define IDC_COINNAME                    1942
#define IDC_ISBASE8                     1943
#define IDC_DEFAULTCOIN                 1943
#define IDC_AreaViewArt                 1943
#define IDC_ISBASE9                     1944
#define IDC_APPLY                       1944
#define IDC_ISBASE10                    1945
#define IDC_MINGEM                      1945
#define IDC_MAXGEM                      1946
#define IDC_JEWELNAME                   1946
#define IDC_MINJEWELRY                  1947
#define IDC_MAXJEWELRY                  1948
#define IDC_COINWEIGHT                  1949
#define IDC_TALKEVENT                   1950
#define IDC_USEEVENT                    1951
#define IDC_EXAMINEEVENT                1951
#define IDC_CASTTIMETYPE                1952
#define IDC_ITEMS                       1953
#define IDC_SAVEWARN                    1954
#define IDC_CHANCE1                     1955
#define IDC_CHANCE2                     1956
#define IDC_CHARGESTOTAL                1956
#define IDC_CHANCE3                     1957
#define IDC_CHARGESDAILY                1957
#define IDC_CHANCE4                     1958
#define IDC_ISNONLETHAL                 1958
#define IDC_CHANCE5                     1959
#define IDC_CHANCE6                     1960
#define IDC_MONSTERNAME                 1960
#define IDC_CHANCE7                     1961
#define IDC_RANDOMMONSTER               1961
#define IDC_CHANCE8                     1962
#define IDC_GIVETOMU                    1962
#define IDC_ALLOWSCRIBING               1962
#define IDC_CHANCE9                     1963
#define IDC_DOORFIRST                   1963
#define IDC_CHANCE10                    1964
#define IDC_CANTRADEITEMS               1964
#define IDC_CHANCE11                    1965
#define IDC_INCITEMS                    1965
#define IDC_CHANCE12                    1966
#define IDC_INCMONSTERS                 1966
#define IDC_CHANCE13                    1967
#define IDC_USEORIGINAL                 1967
#define IDC_INCITEMS2                   1967
#define IDC_CHANCE14                    1968
#define IDC_CLEARMONSTERS               1968
#define IDC_CLEARITEMS                  1969
#define IDC_IDCOST                      1969
#define IDC_MONEYNAME                   1970
#define IDC_BUYBACK                     1971
#define IDC_MODHD                       1973
#define IDC_MODQTY                      1974
#define IDC_MODMEXP                     1975
#define IDC_MODAEXP                     1976
#define IDC_HDAMOUNT                    1977
#define IDC_QTYAMOUNT                   1978
#define IDC_MEXPAMOUNT                  1979
#define IDC_AEXPAMOUNT                  1980
#define IDC_DEFLVL                      1981
#define IDC_DIFFLVL1                    1982
#define IDC_DIFFLVL2                    1983
#define IDC_DIFFLVL                     1983
#define IDC_DIFFLVL3                    1984
#define IDC_DIFFLVL4                    1985
#define IDC_VALUE                       1985
#define IDC_DIFFLVL5                    1986
#define IDC_EDITGLOBALATTRIBUTES        1986
#define IDC_ATTLISTNAME                 1988
#define IDC_DRAWAV                      1989
#define IDC_AVART                       1990
#define IDC_CANBESAVED                  1992
#define IDC_CHECKSYNTAX                 1993
#define IDC_ALLOWEDINCOMBAT             1993
#define IDC_MAXSPELLS                   1994
#define IDC_CHECKSYNTAX2                1994
#define IDC_ISCUMULATIVE                1995
#define IDC_CHECKSYNTAX3                1995
#define IDC_SPECIALSPELLS               1997
#define IDC_IDENTIFYSPELLS              1998
#define IDC_DETECTMAGICSPELLS           1999
#define IDC_SOUNDTEST                   2000
#define IDC_SOUNDTESTQUEUED             2001
#define IDC_SOUNDTESTSTOP               2002
#define IDC_STOPSIMULSOUNDS             2003
#define IDC_TALKLABEL                   2004
#define IDC_BACKGROUNDSOUNDS            2005
#define IDC_EXAMINELABEL                2005
#define IDC_USENIGHTSOUNDS              2006
#define IDC_NIGHTTIMESTART              2007
#define IDC_NIGHTTIMEEND                2008
#define IDC_NIGHTSOUNDS                 2009
#define IDC_SIMULMIDI                   2009
#define IDC_STOPBGNDQUEUE               2010
#define IDC_ALLOWAUTODARKEN             2011
#define IDC_RELOADDESIGN                2013
#define IDC_ENABLEPASSWALLS             2014
#define IDC_DOUBLEFILLWALL              2015
#define IDC_QUADFILLBG                  2016
#define IDC_ENABLEKWIKKLICK             2017
#define IDC_ENABLEDYNACELL              2018
#define IDC_ENABLETILEMAP               2019
#define IDC_MOUSECURSOR                 2020
#define IDC_CANID                       2021
#define IDC_CANAPPRGEMS                 2022
#define IDC_CANAPPRJEWELS               2023
#define IDC_MONSTERMONEY                2024
#define IDC_MONEYTREAS                  2025
#define IDC_MONSTERATTACKMSG            2026
#define IDC_ATTACKDATA                  2027
#define IDC_UndeadType                  2028
#define IDC_TURNUNDEADSOUND             2029
#define IDC_COPYEVENTS                  2030
#define IDC_PASTEEVENTS                 2031
#define IDC_CHOOSEMOVIE                 2032
#define IDC_TESTMOVIE                   2033
#define IDC_CLEARPIC                    2035
#define IDC_ATTACKCOUNT                 2036
#define IDC_STARTEXPTYPE                2037
#define IDC_STARTLVLTYPE                2038
#define IDC_EVENTCOUNT                  2040
#define IDC_QUESTCOUNT                  2041
#define IDC_SPITEMCOUNT                 2042
#define IDC_SPKEYCOUNT                  2043
#define IDC_LEVELCOUNT                  2044
#define IDC_NPCCOUNT                    2045
#define IDC_SIZEONDISK                  2046
#define IDC_ITEMCOUNT                   2047
#define IDC_MONSTERCOUNT                2048
#define IDC_SPELLCOUNT                  2049
#define IDC_FILECOUNT                   2050
#define IDC_MONSTERPIC                  2052
#define IDC_CLEARICON                   2053
#define IDC_JOURNALTEXT                 2054
#define IDC_INPUTBEFORELOOP             2055
#define IDC_PLAYBACKSIZE                2056
#define IDC_LIMITLOOPING                2056
#define IDC_PLAYBACKSIZE2               2057
#define IDC_PLAYBACKSIZE3               2058
#define IDC_BGSOUNDS                    2058
#define IDC_SELECTTITLEFILENAME         2059
#define IDC_USETRANS                    2060
#define IDC_DISPLAYSTYLE                2061
#define IDC_DISPLAYSTYLE2               2062
#define IDC_BLENDWITHPREV               2063
#define IDC_DISPLAYSTYLE3               2064
#define IDC_ADDTITLE                    2065
#define IDC_EDITTITLE                   2066
#define IDC_DELETETITLE                 2067
#define IDC_MOVETITLEUP                 2068
#define IDC_MOVETITLEDOWN               2069
#define IDC_TITLEDELAY                  2070
#define IDC_NUMLOOPS                    2071
#define IDC_NPCTRIGGER                  2072
#define IDC_EXPPTS1                     2073
#define IDC_EXPPTS2                     2074
#define IDC_EXPPTS3                     2075
#define IDC_CANBEDROPPED                2075
#define IDC_ALLOWEXIT                   2076
#define IDC_SupressStepSound            2076
#define IDC_SETTIME                     2077
#define IDC_SupressBumpSound            2077
#define IDC_SILENTPASSING               2078
#define IDC_BASEITEMS                   2079
#define IDC_CLERICITEMS                 2080
#define IDC_FIGHTERITEMS                2081
#define IDC_MUITEMS                     2082
#define IDC_RANGERITEMS                 2083
#define IDC_PALADINITEMS                2084
#define IDC_DRUIDITEMS                  2085
#define IDC_THIEFITEMS                  2086
#define IDC_INROUTESOUND                2086
#define IDC_CASTMSG                     2087
#define IDC_NUMTARGETHELP               2088
#define IDC_TARGRANGEHELP               2089
#define IDC_CHANGEABSOLUTE              2090
#define IDC_UNLOCKKEYS                  2091
#define IDC_KEYNAME1                    2092
#define IDC_KEYNAME2                    2093
#define IDC_KEYNAME3                    2094
#define IDC_KEYNAME4                    2095
#define IDC_KEYNAME5                    2096
#define IDC_KEYNAME6                    2097
#define IDC_KEYNAME7                    2098
#define IDC_KEYNAME8                    2099
#define IDS_HELP_race_Name              2100
#define IDC_PICKKEY1                    2100
#define IDS_HELP_race_Weight            2101
#define IDC_PICKKEY2                    2101
#define IDC_EDITSPECAB                  2101
#define IDS_HELP_race_Height            2102
#define IDC_PICKKEY3                    2102
#define IDS_HELP_race_Age               2103
#define IDC_PICKKEY4                    2103
#define IDC_TEXTEDITOR                  2103
#define IDS_HELP_race_MaxAge            2104
#define IDC_PICKKEY5                    2104
#define IDC_COMPILE                     2104
#define IDS_HELP_race_BaseMovement      2105
#define IDC_PICKKEY6                    2105
#define IDC_TEXTEDITOR2                 2105
#define IDS_HELP_race_AbilityReq        2106
#define IDC_PICKKEY7                    2106
#define IDC_COMPILE2                    2106
#define IDC_PARTYNOEXPERIENCE           2106
#define IDS_HELP_race_MultiClass        2107
#define IDC_PICKKEY8                    2107
#define IDC_ITEMATTACKMSG               2107
#define IDC_ROLLDICE                    2108
#define IDS_HELP_race_SpecialAbility    2108
#define IDC_DISABLETALKIFDEAD           2109
#define IDS_HELP_race_Key               2109
#define IDC_EDITMSGTYPES                2110
#define IDS_HELP_race_ChangeClass       2110
#define IDC_IMPORTALLTEXT               2111
#define IDS_HELP_race_DwarfResistance   2111
#define IDC_BUTTON1                     2112
#define IDC_GPDLTRIGGER                 2112
#define IDC_EDITMSG                     2112
#define IDC_IMPORTFRUAART               2112
#define IDC_EDITSPELLATTRIBS            2112
#define IDC_INVOKESPELL                 2112
#define IDC_DEFAULTMONEY                2112
#define IDC_EDITSCRIPTS                 2112
#define IDC_FIXSPELLS                   2112
#define IDC_FIND                        2112
#define IDC_CAMPMUSIC                   2112
#define IDC_DeleteSpecAbility           2112
#define IDC_CLASSLIST                   2112
#define IDC_Copy                        2112
#define IDS_HELP_race_GnomeResistance   2112
#define IDC_SpecAbsHelp                 2112
#define IDC_Export                      2112
#define IDC_InitSpells                  2112
#define IDC_UnlockSpellHelp             2112
#define IDC_Suggestions                 2112
#define IDC_SelectSkills                2112
#define IDC_MarkIdentified              2112
#define IDC_BG_SLOTS                    2112
#define IDC_ZONE_DATA                   2112
#define IDC_LOGIC_BLOCK                 2112
#define IDC_COMBAT_EVENT                2112
#define IDC_COMBAT_TREASURE             2112
#define IDC_GUIDED_TOUR                 2112
#define IDC_UTILITIES_EVENT             2112
#define IDC_SCRIPTNAME1                 2113
#define IDC_SPELLTRIGGER                2113
#define IDS_HELP_race_FindSecretDoor    2113
#define IDC_Import                      2113
#define IDC_DuplicateSpecAbility        2113
#define IDC_SCRIPTNAME2                 2114
#define IDS_HELP_race_FindSecretDoorSearching 2114
#define IDC_CANBEHALVED                 2115
#define IDS_HELP_race_Skill             2115
#define IDC_SPECABMSGLIST               2116
#define IDS_HELP_race_SkillAdjAbility   2116
#define IDC_SPECABMSG                   2117
#define IDS_HELP_race_SkillAdjBaseclass 2117
#define IDC_HOWMUCHHP                   2118
#define IDS_HELP_race_SkillAdjRace      2118
#define IDC_LITERALORPERCENT            2119
#define IDS_HELP_race_SkillAdjScript    2119
#define IDC_LITERALORPERCENT2           2120
#define IDC_LITERALORPERCENT3           2121
#define IDC_EDITORRES640                2122
#define IDC_EDITORRES800                2123
#define ID_UPDATEGAMERES                2123
#define IDC_EDITORRES1024               2124
#define IDC_UPDATEDESIGNCONFIG          2124
#define IDC_EDITORRES1152               2125
#define IDC_TARGRANGELABEL              2125
#define IDC_TARG_P2_LABEL               2125
#define IDC_EDITORRES1280               2126
#define IDC_TARGNUMBERLABEL             2126
#define IDC_TARG_P1_LABEL               2126
#define IDC_ONLYUPCLOSE1                2127
#define IDC_TARG_P3_LABEL               2127
#define IDC_ONLYUPCLOSE2                2128
#define IDC_USECURRENTART               2128
#define IDC_TARG_P4_LABEL               2128
#define IDC_ONLYUPCLOSE3                2129
#define IDC_SILENTGIVETOACTIVE          2129
#define IDC_TARG_P5_LABEL               2129
#define IDC_ONLYUPCLOSE4                2130
#define IDC_SCRIPTFUNCTIONLIST          2130
#define IDC_ONLYUPCLOSE5                2131
#define IDC_CANBETRADEDROPSOLDDEP       2133
#define IDC_SPELLSCRIPTS                2134
#define IDC_LINGERS                     2135
#define IDC_LINGERAFFECTSONCEONLY       2136
#define IDC_USEHITDICE                  2137
#define IDC_USEHITPOINTS                2138
#define IDC_USEALPHA                    2139
#define IDC_ALPHAVALUE                  2140
#define IDC_PARTYLIST                   2142
#define IDC_Record                      2143
#define IDC_SCRIPTCOMBO                 2144
#define IDC_CHANGEREMOVEALL             2145
#define IDC_CANBEDISPELLED              2146
#define IDC_SEARCHTEXT                  2147
#define IDC_SEARCH                      2151
#define IDC_MATCHCASE                   2153
#define IDC_MATCHWHOLESTRING            2154
#define IDC_SRCHEVENTTEXT               2155
#define IDC_SEARCHEVENTID               2156
#define IDC_WHICHVAULT                  2157
#define IDC_BUYITEMSSOLDONLY            2159
#define IDC_EACHTALEONCEONLY            2160
#define IDC_AUTOSCRIBEATLEVELCHANGE     2161
#define IDC_AUTOSCRIBE                  2161
#define IDC_QUANTITYTYPE                2162
#define IDC_QUANTITYTYPE2               2163
#define IDC_DICESIDES                   2164
#define IDC_DICEBONUS                   2166
#define IDC_IDENTIFYALLITEMS            2166
#define IDC_TIMEEVENTNAME               2167
#define IDC_TIMEEVENT_NUM               2168
#define IDC_TIMEEVENTSPIN               2169
#define IDC_TIMEABSOLUTE                2170
#define IDC_TIMEREPEAT                  2171
#define IDC_Alpha                       2173
#define IDC_Numeric                     2174
#define IDC_Warning                     2175
#define IDC_SCRIBABLE                   2176
#define IDC_xRefList                    2177
#define IDC_OneReference                2179
#define IDC_EXISTS                      2180
#define IDC_ZeroReference               2181
#define IDC_NewAbilityName              2181
#define IDC_TwoReference                2182
#define IDC_MISSING                     2183
#define IDC_DisplayFirst                2184
#define IDC_Include                     2184
#define IDC_Constant                    2185
#define IDC_Variable                    2186
#define IDC_CLASSES                     2187
#define IDC_Paste                       2188
#define IDC_ContextNote                 2189
#define IDC_IntegerTable                2190
#define IDC_DurationText1               2194
#define IDC_DurationText2               2195
#define IDC_TestMode                    2196
#define IDS_HELP_baseclass_Name         2200
#define IDS_HELP_baseclass_PrimeReq     2201
#define IDS_HELP_baseclass_PrimeAbility 2201
#define IDS_HELP_baseclass_AbilityReq   2202
#define IDS_HELP_baseclass_AllowRace    2203
#define IDS_HELP_baseclass_ExpLevel     2204
#define IDS_HELP_baseclass_AllowAlign   2205
#define IDC_MAX                         2205
#define IDS_HELP_baseclass_SpecialAbility 2206
#define IDC_MIN                         2206
#define IDS_HELP_baseclass_Key          2207
#define IDS_HELP_baseclass_MaxSpellLevelByPrime 2208
#define IDS_HELP_baseclass_SaveVs       2209
#define IDC_Class_Baseclass             2209
#define IDC_ClassTag                    2209
#define IDS_HELP_baseclass_PrimeCastingAbility 2210
#define IDC_IMPORT_GLOBAL               2210
#define IDS_HELP_baseclass_TurnUndeadLevel 2211
#define IDC_EXPORT_GLOBAL               2211
#define IDC_RACE                        2211
#define IDS_HELP_baseclass_BackstabAbility 2212
#define IDC_NEW                         2212
#define IDS_HELP_baseclass_BackstabLevel 2213
#define IDS_HELP_baseclass_RangerBonusLevel 2214
#define IDS_HELP_baseclass_HitDice      2215
#define IDC_Help                        2215
#define IDS_HELP_baseclass_Skill        2216
#define IDC_Highlight                   2216
#define IDS_HELP_baseclass_SkillAdjAbility 2217
#define IDC_DRINK                       2217
#define IDS_HELP_baseclass_SkillAdjBaseclass 2218
#define IDC_DRUNK                       2218
#define IDS_HELP_baseclass_SkillAdjRace 2219
#define IDC_REPLACE                     2219
#define IDS_HELP_baseclass_SpellBonusAbility 2220
#define IDC_ID_Display_Name             2220
#define IDS_HELP_baseclass_BonusSpells  2221
#define IDS_HELP_baseclass_BaseSpellLevels 2222
#define IDC_HelpText                    2222
#define IDS_HELP_baseclass_THAC0        2223
#define IDC_SAVEVERSUS                  2223
#define IDS_HELP_baseclass_MaxNumSpellsByPrime 2224
#define IDC_WHO_TRIES                   2224
#define IDS_HELP_baseclass_SkillAdjScript 2225
#define IDC_WALL_SLOTS                  2225
#define IDS_HELP_baseclass_BonusXP      2226
#define IDC_SaveResultLabel             2226
#define IDC_SaveVsLabel                 2227
#define IDS_HELP_baseclass_PrimeRequisite 2227
#define IDC_EntryMarkerName             2228
#define IDC_DestinationMarkerName       2231
#define IDC_Equals                      2234
#define IDC_NotEqual                    2235
#define IDC_VariableName                2237
#define IDC_RADIO4                      2238
#define IDC_RADIO9                      2239
#define IDC_RADIO7                      2240
#define IDC_RADIO8                      2241
#define IDC_Condition                   2243
#define IDC_ExitMarkerName              2244
#define IDC_Manipulate                  2245
#define IDC_Action                      2246
#define IDC_Local                       2247
#define IDC_LevelSelect                 2250
#define IDC_EDIT1                       2253
#define IDC_ItemTriggerTag              2254
#define IDC_SpItemTriggerTag            2255
#define IDC_SpKeyTriggerTag             2256
#define IDC_QuestTriggerTag             2257
#define IDC_NPCTriggerTag               2258
#define IDC_RaceTag                     2259
#define IDC_FacingTag                   2260
#define IDC_GenderTag                   2261
#define IDC_SpellTriggerTag             2262
#define IDC_PartyXTag                   2263
#define IDC_PartyYTag                   2264
#define IDC_QuestStageTag               2265
#define IDC_QuestStageDoc               2266
#define IDC_PChanceTag                  2267
#define IDS_HELP_ability_Name           2300
#define IDS_HELP_ability_Abbrev         2301
#define IDS_HELP_ability_Roll           2302
#define IDS_HELP_ability_Modify         2303
#define IDS_HELP_ability_Adjust         2304
#define IDS_HELP_ability_Key            2305
#define IDS_HELP_class_Name             2400
#define IDS_HELP_class_HitDiceBonus     2401
#define IDS_HELP_class_HitDiceBonusAttr 2402
#define IDS_HELP_class_HitDiceBaseclass 2403
#define IDS_HELP_class_StrengthBonusDice 2404
#define IDS_HELP_class_StartingEquipment 2405
#define IDS_HELP_class_HitDiceLevelBonus 2406
#define IDS_HELP_trait_Name             2500
#define IDS_HELP_class_Baseclass        2501
#define IDS_HELP_trait_Adjust           2502
#define IDS_HELP_trait_SpecialAbility   2503
#define IDS_HELP_trait_Key              2504
#define IDS_HELP_spellgroup_Name        2600
#define IDS_HELP_spellgroup_Spell       2601
#define IDS_HELP_spellgroup_Spellgroup  2602
#define IDS_HELP_class_SpecialAbility   2603
#define IDS_HELP_spellgroup_SpecialAbility 2604
#define IDS_HELP_class_Key              2605
#define IDS_HELP_spellgroup_Key         2606
#define IDS_HELP_NPC_Name               2700
#define IDS_HELP_NPC_Version            2701
#define IDS_HELP_NPC_Type               2702
#define IDS_HELP_NPC_Race               2703
#define IDS_HELP_NPC_Gender             2704
#define IDS_HELP_NPC_Class              2705
#define IDS_HELP_NPC_Alignment          2706
#define IDS_HELP_NPC_AllowInCombat      2707
#define IDS_HELP_NPC_Status             2708
#define IDS_HELP_NPC_Specabs            2709
#define IDS_HELP_level_Width            2800
#define IDS_HELP_level_none             2800
#define IDS_HELP_event_none             2900
#define ID_ITEMS_WALL                   32771
#define ID_ITEMS_DOOR                   32772
#define ID_ITEMS_BACKDROP               32773
#define ID_ITEM_ZONE                    32774
#define ID_VIEW_WALLSETS                32775
#define ID_VIEW_BACKDROPS               32776
#define ID_VIEW_ZONES                   32777
#define ID_FILE_NEW_MAP                 32778
#define ID_FILE_OPEN_MAP                32780
#define ID_ITEMS_STARTLOC               32781
#define ID_ITEMS_EVENT                  32782
#define ID_VIEW_INNS                    32783
#define ID_PASSTHRUWALLS                32783
#define ID_VIEW_SHOPS                   32784
#define ID_VIEW_CHARS                   32784
#define ID_VIEW_TAVERNS                 32785
#define ID_FILLUNUSEDMAP                32785
#define ID_VIEW_TEMPLES                 32786
#define ID_FILLALLMAP                   32786
#define ID_VIEW_HALLS                   32787
#define ID_ITEMS_ACCESS                 32787
#define ID_VIEW_CHARACTERS              32788
#define ID_VIEW_GLOBALDATA              32788
#define ID_VIEW_LEVELDATA               32789
#define ID_VIEW_KEYS                    32790
#define ID_VIEW_SPECIALITEMS            32791
#define ID_VIEW_COMBATWALLS             32792
#define ID_VIEW_ENTRYPOINTS             32793
#define ID_VIEWAREAMAP                  32794
#define ID_FILE_SAVE_MAP                32796
#define ID_FILE_SAVE_AS_MAP             32797
#define ID_VIEW_SPIC_POOL               32798
#define ID_VIEW_ICON_POOL               32799
#define ID_EDIT_ITEMS                   32800
#define ID_EDIT_SPELLS                  32801
#define ID_EDIT_MONSTERS                32802
#define ID_IMPORTEXPORT                 32803
#define ID_ITEMS_ENTRYPOINT             32804
#define ID_CLEAR_LEVELDATA              32810
#define ID_VIEW_STEPEVENTS              32812
#define ID_CLEAR_DESIGNDATA             32821
#define ID_DOUBLEFILLWALLSLOT           32822
#define ID_IMPORTFRUA                   32824
#define ID_EXPORTFRUA                   32825
#define ID_VIEW_EVENTS                  32826
#define ID_UNDOLAST                     32827
#define ID_CLEAR_DESIGNFOLDER           32828
#define ID_VALIDATE_DESIGN              32830
#define ID_GAME_VERSION                 32831
#define ID_APP_HelpWallEdit             32832
#define ID_ACCESSOPTIONS                32834
#define IDC_TILEMAPDATA                 32835
#define ID_EDIT_CONFIG                  32836
#define ID_RELOAD_CONFIG                32837
#define ID_MAPpopCancel                 32840
#define ID_MAPpop_EditEvent             32841
#define ID_HOMEPAGE                     32842
#define ID_GLOBAL_TESTSAVEDDESIGN       32844
#define ID_GLOBAL_TESTSAVEDDESIGNFROMSTART 32845
#define ID_DOWNLOADS                    32847
#define ID_LOG_EVENT_TEXT               32848
#define ID_QUADFILLBGSLOT               32849
#define ID_FILLALLMAPZONE               32851
#define ID_FILLALLMAPDISTANTBGON        32852
#define ID_LEVEL_FILLALLMAP_SHOWDISTANTBACKGROUNDS_OFF 32853
#define ID_FILLALLMAPDISTANTBGOFF       32854
#define ID_SETRES640x480                32856
#define ID_SETRES800x600                32857
#define ID_SETRES1024x768               32858
#define ID_SETRES1152x864               32859
#define ID_SETRES1280x1024              32860
#define ID_TOGGLE_TOPMOST               32861
#define ID_LAUNCHUACONFIG               32862
#define ID_FILLALLBACKDROP_ALLDIR       32863
#define ID_FILLALLBACKDROP_NORTHDIR     32864
#define ID_FILLALLBACKDROP_EASTDIR      32865
#define ID_FILLALLBACKDROP_SOUTHDIR     32866
#define ID_FILLALLBACKDROP_WESTDIR      32867
#define ID_FILLUNUSEDBACKDROP_ALLDIR    32868
#define ID_FILLUNUSEDBACKDROP_NORTHDIR  32869
#define ID_FILLUNUSEDBACKDROP_EASTDIR   32870
#define ID_FILLUNUSEDBACKDROP_SOUTHDIR  32871
#define ID_FILLUNUSEDBACKDROP_WESTDIR   32872
#define ID_APP_HELPCONTENTS             32873
#define ID_GLOBAL_VIEWARTASTRANSPARENT  32874
#define ID_EDITOROPTIONS                32875
#define ID_LAUNCHDCCONFIG               32876
#define ID_GAME_STATS                   32877
#define ID_VIEWJOURNAL                  32878
#define ID_APP_SCREENCAPTURE            32879
#define ID_GLOBAL_SETTESTPARTY          32880
#define ID_GLOBAL_TESTSAVEDDESIGN_VIEWERRORLOG 32881
#define ID_GAME_ERRORLOG                32882
#define ID_EDIT_SPECIAL_ABILITIES       32883
#define ID_TEST_SPECIAL_ABILITIES       32884
#define IDM_SkillConsistence            32885
#define IDM_CheckSkills                 32886
#define IDS_STRING61204                 61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32887
#define _APS_NEXT_CONTROL_VALUE         2268
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
