function Items() {
    this.WeaponHand = UAFUtil.StringToBase38('WEAPON');
    this.ShieldHand = UAFUtil.StringToBase38('SHIELD');
    this.BodyArmor = UAFUtil.StringToBase38('ARMOR');
    this.AmmoQuiver = UAFUtil.StringToBase38('QUIVER');
    this.Hands = UAFUtil.StringToBase38('HANDS');
    this.Head = UAFUtil.StringToBase38('HEAD');
    this.Waist = UAFUtil.StringToBase38('WAIST');
    this.BodyRobe = UAFUtil.StringToBase38('ROBE');
    this.Back = UAFUtil.StringToBase38('CLOAK');
    this.Feet = UAFUtil.StringToBase38('FEET');
    this.Fingers = UAFUtil.StringToBase38('FINGER');
    this.Cannot = UAFUtil.StringToBase38('CANNOT');
    this.NotReady = UAFUtil.StringToBase38('NOTRDY');
    this.Arms = UAFUtil.StringToBase38('ARMS');
    this.Legs = UAFUtil.StringToBase38('LEGS');
    this.Face = UAFUtil.StringToBase38('FACE');
    this.Neck = UAFUtil.StringToBase38('NECK');
    this.Pack = UAFUtil.StringToBase38('PACK');
    this.Undefined = UAFUtil.StringToBase38('UNDEF');
}